# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19bKIldHD5_aw7ESfbefw0-XoElDSH5so
"""

# تثبيت المكتبات اللازمة للمشروعين
!pip install transformers[torch] datasets arabert farasa pyarabic

from transformers import pipeline
import torch

# التأكد من استخدام GPU
device = 0 if torch.cuda.is_available() else -1

print("جاري تحميل النموذج العالمي المستقر (Multilingual BERT)...")

try:
    # هذا النموذج يدعم 104 لغات من ضمنها العربية ومتاح دائماً
    model_id = "Davlan/bert-base-multilingual-cased-ner-hrl"

    ner_model = pipeline(
        "ner",
        model=model_id,
        tokenizer=model_id,
        aggregation_strategy="simple",
        device=device
    )
    print("✅ تم التحميل بنجاح! هذا النموذج العالمي جاهز الآن لاستخراج الكيانات العربية.")
except Exception as e:
    print(f"❌ خطأ غير متوقع: {e}")

def analyze_final_ner(text):
    results = ner_model(text)
    print(f"\n--- نتائج استخراج الكيانات (Multilingual BERT) ---")
    print(f"النص: {text}\n")
    print(f"{'الكيان':<25} | {'النوع':<15}")
    print("-" * 45)

    for entity in results:
        # تحويل الرموز لأسماء عربية سهلة
        label_map = {"PER": "شخص", "LOC": "مكان", "ORG": "منظمة"}
        etype = label_map.get(entity['entity_group'], entity['entity_group'])
        print(f"{entity['word']:<25} | {etype:<15}")

# تجربة حقيقية
analyze_final_ner("سافر محمد محمد الأسود من مدينة دبي إلى الرياض لزيارة شركة أرامكو")